#!/usr/bin/env sh
# hands — standalone installer.
#
#   curl -fsSL https://hands-cc.dev/install.sh | sh
#
# Installs the `hands` CLI into ~/.hands (lib + bin) with no npm step: the
# bundles are committed in the repo, so this is a download and a chmod.
#
# Why standalone at all, when the Claude Code plugin already puts `hands` on
# PATH? Because the plugin's copy only moves when you remember to update the
# plugin, and a stale copy is invisible: the symptom is "that command doesn't
# exist" while your checkout plainly has it. A standalone install is one you
# control, and `hands version` / `hands doctor` will tell you when the two
# disagree.
#
# POSIX sh on purpose — this runs before anything of ours exists.

set -eu

REPO="${HANDS_REPO:-hands-dev/hands}"
REF="${HANDS_REF:-main}"
PREFIX="${HANDS_PREFIX:-$HOME/.hands}"
# HANDS_BLOB_ORIGIN is the Vercel Blob store the payload is published to, keyed by commit
# (hands#94) — installer/<commit>/{cli.mjs,...}, plus one mutable installer/latest.json pointer
# that "main" resolves through. Empty by default until the store exists in production; once it
# does, the literal default below becomes the one-line cutover install.sh's own header always
# said was coming. Until then this falls back to raw.githubusercontent exactly as before —
# nothing here changes behavior for anyone not explicitly opting in via this var.
BLOB_ORIGIN="${HANDS_BLOB_ORIGIN:-}"
# HANDS_BASE overrides where the payload comes from outright — an internal mirror, or a local
# checkout (file:///path/to/hands/plugin/dist) when testing the installer itself. Takes priority
# over everything below.
BASE="${HANDS_BASE:-}"

LIB="$PREFIX/lib"
BIN="$PREFIX/bin"

say() { printf '%s\n' "$*"; }
die() { printf 'hands: %s\n' "$*" >&2; exit 1; }

# ── preflight ───────────────────────────────────────────────────────────────
command -v node >/dev/null 2>&1 || die "node is required (>= 22.5) and was not found on PATH"

node_ok=$(node -e 'const [a,b]=process.versions.node.split(".").map(Number);process.stdout.write(a>22||(a===22&&b>=5)?"y":"n")' 2>/dev/null || printf 'n')
[ "$node_ok" = "y" ] || die "node >= 22.5 is required (node:sqlite); found $(node -v 2>/dev/null || echo none)"

if command -v curl >/dev/null 2>&1; then
  fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
  fetch() { wget -qO "$2" "$1"; }
else
  die "need curl or wget to download"
fi

# ── download to a temp dir, move into place only once everything arrived ────
# A half-written CLI on PATH is worse than no CLI: it fails in ways that look
# like bugs in hands rather than a truncated download.
tmp=$(mktemp -d "${TMPDIR:-/tmp}/hands-install.XXXXXX") || die "could not create a temp dir"
trap 'rm -rf "$tmp"' EXIT INT TERM

# ── resolve BASE ──────────────────────────────────────────────────────────
# Priority: HANDS_BASE (explicit override, unconditional) → Blob, if configured, resolving
# "latest" through installer/latest.json ONCE here (never re-resolved mid-download — everything
# fetched below comes from one immutable commit tree, so a publish that lands between this line
# and the last file downloaded can't produce a mixed-version install) → raw.githubusercontent at
# the pinned ref, same as always.
if [ -z "$BASE" ] && [ -n "$BLOB_ORIGIN" ]; then
  if [ "$REF" = "main" ]; then
    fetch "$BLOB_ORIGIN/installer/latest.json" "$tmp/latest.json" || die "download failed: $BLOB_ORIGIN/installer/latest.json"
    [ -s "$tmp/latest.json" ] || die "downloaded an empty file: installer/latest.json"
    blob_commit=$(node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).commit||"")' "$tmp/latest.json" 2>/dev/null || printf '')
    [ -n "$blob_commit" ] || die "installer/latest.json has no commit — malformed publish"
  else
    blob_commit="$REF"
  fi
  BASE="$BLOB_ORIGIN/installer/$blob_commit"
  REF="$blob_commit"
elif [ -z "$BASE" ]; then
  BASE="https://raw.githubusercontent.com/${REPO}/${REF}/plugin/dist"
fi

say "downloading hands from ${REPO}@${REF}…"
for f in cli.mjs cli-impl.mjs BUILD.json; do
  fetch "$BASE/$f" "$tmp/$f" || die "download failed: $BASE/$f"
  [ -s "$tmp/$f" ] || die "downloaded an empty file: $f"
done

# Dashboard assets (hands#151): the manifest is generated by bundle.mjs from
# the actual assets/ dir it just built, so this list can never drift out of
# sync the way a second hardcoded copy in this script would. Without these,
# `hands serve` refuses to start (it used to serve a 200 shell that could
# never render — see serve.ts's ServeError).
fetch "$BASE/assets/MANIFEST.txt" "$tmp/assets-manifest.txt" || die "download failed: $BASE/assets/MANIFEST.txt"
[ -s "$tmp/assets-manifest.txt" ] || die "downloaded an empty file: assets/MANIFEST.txt"
mkdir -p "$tmp/assets"
while IFS= read -r asset; do
  [ -n "$asset" ] || continue
  mkdir -p "$tmp/assets/$(dirname "$asset")"
  fetch "$BASE/assets/$asset" "$tmp/assets/$asset" || die "download failed: $BASE/assets/$asset"
  [ -s "$tmp/assets/$asset" ] || die "downloaded an empty file: assets/$asset"
done < "$tmp/assets-manifest.txt"

# Sanity-check the payload actually parses before we put it on PATH.
node --input-type=module -e "await import('file://$tmp/cli-impl.mjs')" >/dev/null 2>&1 \
  || say "  (note: could not pre-verify the bundle; continuing)"

mkdir -p "$LIB" "$BIN"
rm -rf "$LIB/assets"
mv -f "$tmp/assets" "$LIB/assets"
for f in cli.mjs cli-impl.mjs BUILD.json; do
  mv -f "$tmp/$f" "$LIB/$f"
done

cat > "$BIN/hands" <<EOF
#!/usr/bin/env bash
# hands — standalone CLI shim (installed by hands-cc.dev/install.sh)
set -euo pipefail
exec node --no-warnings "$LIB/cli.mjs" "\$@"
EOF
chmod +x "$BIN/hands"

version=$(node -e 'try{process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).version||"?")}catch(e){process.stdout.write("?")}' "$LIB/BUILD.json" 2>/dev/null || printf '?')
say "✔ hands ${version} installed → ${BIN}/hands"

# ── PATH advice (never edit the user's shell rc uninvited) ──────────────────
case ":${PATH}:" in
  *":$BIN:"*)
    say ""
    say "Run: hands doctor"
    ;;
  *)
    say ""
    say "Add it to your PATH:"
    say ""
    say "  export PATH=\"$BIN:\$PATH\""
    say ""
    say "…then: hands doctor"
    ;;
esac
