// generated by engine/scripts/extract-mobile-types.mjs from engine/src/snapshot.ts — do not edit by hand
// the local-only snapshot shape apps/mobile reads off a LAN "hands serve" instance's /api/events

export type AgentState = "active" | "idle" | "offline";

export interface MobileAgent {
  id: string;
  state: AgentState;
  online: boolean;
  focus: string | null;
  ticket: string | null;
}

export interface MobileTask {
  id: number;
  title: string;
  from: string;
  assignee: string;
  state: string;
  priority: string | null;
  dish: string | null;
  at: number;
}

export interface MobileQuestion {
  id: number;
  asker: string;
  question: string;
  state: string;
  recommendation: string | null;
  priority: string | null;
  at: number;
}

export interface MobileSnapshot {
  now: number;
  agents: MobileAgent[];
  tasks: MobileTask[];
  questions: MobileQuestion[];
  counts: {
    activeTasks: number;
    returnedTasks: number;
    openQuestions: number;
    needsHuman: number;
  };
}
